controllers:
  main:
    serviceAccount:
      identifier: &app fingerjoin

    containers:
      main:
        enabled: true
        image:
          repository: ghcr.io/m00nwtchr/fingerjoin
          tag: master
          pullPolicy: IfNotPresent

        # env:
        #   CLUSTER_DOMAIN: cluster.local  # override if your cluster uses a custom domain
        #   PORT: "8080"                   # override the listen port

        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: [ALL]}
          readOnlyRootFilesystem: true
          privileged: false

        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            memory: 128Mi
            ephemeral-storage: 256Mi

    pod:
      securityContext:
        runAsUser: 65532
        runAsNonRoot: true
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch
        seccompProfile:
          type: RuntimeDefault

serviceAccount:
  fingerjoin:
    enabled: true

service:
  main:
    ports:
      http:
        port: 80
        targetPort: 8080

rbac:
  roles:
    fingerjoin:
      type: ClusterRole
      label: "{{ .Release.Name }}-fingerjoin"
      rules:
        - apiGroups: ["gateway.networking.k8s.io"]
          resources: ["httproutes"]
          verbs: ["get", "list", "watch"]
  bindings:
    fingerjoin:
      type: ClusterRoleBinding
      label: "{{ .Release.Name }}-fingerjoin"
      subjects:
        - kind: ServiceAccount
          name: *app
          namespace: "{{ .Release.Namespace }}"
      roleRef:
        kind: ClusterRole
        identifier: *app
